In [22]:
import pandas as pd

In [23]:
#Crear un dataFRame con 1,000,000 de registros
cantidad=1000000

In [24]:
import random

In [25]:
influencers = ["Fernanfloo", "Vegueta777", "Aldo_Geo", "ElMariana", "Amlo", "Donald Trump", "Beniju", "Elonk Musk", "Vladimir Putin"]
tipos_post = ["Imagen", "Reel", "Video", "Carrusel"]

In [26]:
df_instagram = pd.DataFrame({
    "influencer": [random.choice(influencers) for _ in range(cantidad)],
    "likes": [random.randint(1000, 575000) for _ in range(cantidad)],
    "comentarios": [random.randint(1000, 50000)for _ in range(cantidad)],
    "fecha": [random.randint(2020, 2026) for _ in range(cantidad)],
    "tipo_post": [random.choice(tipos_post) for _ in range(cantidad)]
})

In [27]:
df_instagram

            influencer   likes  comentarios  fecha tipo_post
0            ElMariana  187903        44798   2024     Video
1             Aldo_Geo  504003        44369   2026      Reel
2             Aldo_Geo  188393        47617   2021      Reel
3               Beniju  341772        40082   2025  Carrusel
4       Vladimir Putin  227393        18591   2024      Reel
...                ...     ...          ...    ...       ...
999995          Beniju  198405         1213   2024      Reel
999996            Amlo   39321        17143   2022     Video
999997      Vegueta777  372639         9328   2023  Carrusel
999998      Elonk Musk  478882        24111   2022    Imagen
999999       ElMariana  163924        21180   2020     Video

[1000000 rows x 5 columns]

In [28]:
df_instagram.dtypes

influencer     object
likes           int64
comentarios     int64
fecha           int64
tipo_post      object
dtype: object

In [29]:
df_instagram.memory_usage(deep=True)

Index               132
influencer     58223567
likes           8000000
comentarios     8000000
fecha           8000000
tipo_post      54751618
dtype: int64

In [30]:
df_instagram.memory_usage(deep=True).sum() /1024**2

np.float64(130.6298418045044)